import "./globals.css";
import NavBar from "./components/NavBar";
import { Nunito, Roboto_Mono } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunito = Nunito({
  subsets: ["latin"],
  weight: "800",
  display: "swap",
  variable: "--font-nunito",
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
  weight: "500",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${roboto_mono.variable}`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
